language: python

python:
  - 3.5
  
install:
  - pip install -r requirements.txt
  
script:
    - python test.py

deploy:
  - provider: pages
  - github_token: $GITHUB_TOKEN
  - skip_cleanup: true

on:
    branch: master
